### PR TITLE
Use temporary directory

### PR DESCRIPTION
**Pull request by ybznek**
https://github.com/OpenSCAP/openscap/issues/329

### CODE REVIEW

**Comment by ybznek** [comment]
Some issue I've spotted. Wait with merging, I will check it.

**Comment by ybznek** [comment]
The openscap-daemon returned: [Errno 39] Directory not empty: '/tmp/tmp805bx__2'
Seems that after scan isn't container directory properly deleted. So deletion of root directory isn't successfull.

**Comment by mpreisler** [comment]
> Some issue I've spotted. Wait with merging, I will check it.

Can you outline the issues? One issue was not deleting the mount-dir but that seems to be fixed in 01a58bb.

Can this be merged now?

**Comment by ybznek** [comment]
Yes, I've tried it with the fix.
We can merge it, now.

**Pull request merged**
