### PR TITLE
Make local RPM

### PR DESCRIPTION
**Pull request by baude**
Add the ability to build an rpm from the local
git repo.

### CODE REVIEW

**Comment by ybznek** [comment]
[add to whitelist] [ok to test]

**Comment by jan-cerny** [comment]
@baude Is it really necessary to have a downstream spec file in upstream repository? We will have to maintain them twice - once in downstream and once in upstream. For example, in OpenSCAP, we used to have them upstream, but we removed them. Moreover, this spec file is Fedora specific. What about other distributions where openscap-deamon will be included?

**Comment by baude** [comment]
I was just thinking it would be very convenient to have a way to make a local RPM given all the changes we've been doing as well as ease to build a docker image.  If you don't agree, close as such ... I wont be offended.

**Comment by mpreisler** [comment]
I agree with @jan-cerny, let's not add a spec to upstream git repo. The spec can be downloaded from Fedora git repo if necessary.

**Pull request closed without merging**
